version: "3.7"

volumes:
  keycloak:

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./src/keycloak/:/opt/keycloak/data/import/
    restart: always
    command:
      - "-Dkeycloak.import=/opt/keycloak/data/import/"
      - "start-dev"
